// Package e2e runs the ported generator against the fixtures in
// test/valid-data, comparing generated schemas with the checked-in
// schema.json files. The fixture list lives in test/fixtures-manifest.json
// (generated by tools/extract_fixtures).
package e2e

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"

	"github.com/vega/ts-json-schema-generator-go/internal/config"
	"github.com/vega/ts-json-schema-generator-go/internal/factory"
	"github.com/vega/ts-json-schema-generator-go/internal/fixtures"
	"github.com/vega/ts-json-schema-generator-go/internal/testutil"
)

var repoRoot = testutil.RepoRoot

// requireNpmSources skips the test when an npm-installed source file is
// missing, except in CI (CI env var set), where a missing file means
// `npm ci` failed and the test must fail instead of passing silently.
func requireNpmSources(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err != nil {
		msg := fmt.Sprintf("npm sources not installed (run npm ci): %v", err)
		if os.Getenv("CI") != "" {
			t.Fatal(msg)
		}
		t.Skip(msg)
	}
}

func TestMain(m *testing.M) {
	testutil.ChdirRepoRoot()
	os.Exit(m.Run())
}

func TestValidData(t *testing.T) {
	root := repoRoot(t)

	data, err := os.ReadFile(filepath.Join(root, "test", "fixtures-manifest.json"))
	if err != nil {
		t.Fatalf("cannot read fixtures manifest (run `go run ./tools/extract_fixtures`): %v", err)
	}
	var manifest []fixtures.Entry
	if err := json.Unmarshal(data, &manifest); err != nil {
		t.Fatalf("cannot parse fixtures manifest: %v", err)
	}

	seen := map[string]int{}
	for _, entry := range manifest {
		seen[entry.Name]++
		testName := entry.Name
		if seen[entry.Name] > 1 {
			testName = fmt.Sprintf("%s#%d", entry.Name, seen[entry.Name])
		}
		t.Run(testName, func(t *testing.T) {
			if entry.Skip != "" {
				t.Skipf("skipped by manifest: %s", entry.Skip)
			}
			runFixture(t, root, entry)
		})
	}
}

func runFixture(t *testing.T, root string, entry fixtures.Entry) {
	t.Helper()

	cfg, err := fixtureConfig(root, entry)
	if err != nil {
		t.Fatal(err)
	}

	generator, release, err := factory.CreateGenerator(cfg)
	if err != nil {
		t.Fatalf("CreateGenerator: %v", err)
	}
	defer release()

	actualSchema, err := generator.CreateSchema(entry.Types)
	if err != nil {
		t.Fatalf("CreateSchema: %v", err)
	}

	actualJSON, err := json.Marshal(actualSchema)
	if err != nil {
		t.Fatalf("marshal generated schema: %v", err)
	}
	var actual any
	if err := json.Unmarshal(actualJSON, &actual); err != nil {
		t.Fatalf("round-trip generated schema: %v", err)
	}

	expectedJSON, err := os.ReadFile(filepath.Join(root, "test", "valid-data", entry.Name, "schema.json"))
	if err != nil {
		t.Fatalf("read expected schema: %v", err)
	}
	var expected any
	if err := json.Unmarshal(expectedJSON, &expected); err != nil {
		t.Fatalf("parse expected schema: %v", err)
	}

	if !reflect.DeepEqual(actual, expected) {
		var diffs []string
		diffJSON("$", expected, actual, &diffs)
		if len(diffs) > 20 {
			diffs = append(diffs[:20], fmt.Sprintf("... and %d more differences", len(diffs)-20))
		}
		t.Errorf("schema mismatch:\n%s", strings.Join(diffs, "\n"))
	}
}

func fixtureConfig(root string, entry fixtures.Entry) (*config.Config, error) {
	if err := fixtures.ValidateConfig(entry.Config); err != nil {
		return nil, fmt.Errorf("manifest: %w", err)
	}

	cfg := config.Default()
	// Type checking the fixtures is slow and is covered upstream; skip it.
	cfg.SkipTypeCheck = true
	if entry.Config != nil {
		data, err := json.Marshal(entry.Config)
		if err != nil {
			return nil, err
		}
		if err := json.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("manifest config: %w", err)
		}
	}

	cfg.Types = entry.Types
	glob := "*.ts"
	if entry.MainTsOnly {
		glob = "main.ts"
	}
	cfg.Path = filepath.Join(root, "test", "valid-data", entry.Name, glob)
	if _, ok := entry.Config["tsconfig"]; ok && !filepath.IsAbs(cfg.Tsconfig) {
		cfg.Tsconfig = filepath.Join(root, cfg.Tsconfig)
	}
	return cfg, nil
}

// diffJSON records human-readable differences between two decoded JSON
// values.
func diffJSON(path string, expected, actual any, diffs *[]string) {
	if reflect.DeepEqual(expected, actual) {
		return
	}
	switch exp := expected.(type) {
	case map[string]any:
		act, ok := actual.(map[string]any)
		if !ok {
			*diffs = append(*diffs, fmt.Sprintf("%s: expected object, got %s", path, describeJSON(actual)))
			return
		}
		keys := map[string]bool{}
		for key := range exp {
			keys[key] = true
		}
		for key := range act {
			keys[key] = true
		}
		sorted := make([]string, 0, len(keys))
		for key := range keys {
			sorted = append(sorted, key)
		}
		sort.Strings(sorted)
		for _, key := range sorted {
			expValue, expOK := exp[key]
			actValue, actOK := act[key]
			childPath := path + "." + key
			switch {
			case !expOK:
				*diffs = append(*diffs, fmt.Sprintf("%s: unexpected key (got %s)", childPath, describeJSON(actValue)))
			case !actOK:
				*diffs = append(*diffs, fmt.Sprintf("%s: missing key (want %s)", childPath, describeJSON(expValue)))
			default:
				diffJSON(childPath, expValue, actValue, diffs)
			}
		}
	case []any:
		act, ok := actual.([]any)
		if !ok {
			*diffs = append(*diffs, fmt.Sprintf("%s: expected array, got %s", path, describeJSON(actual)))
			return
		}
		if len(exp) != len(act) {
			*diffs = append(*diffs, fmt.Sprintf("%s: array length mismatch: want %d, got %d", path, len(exp), len(act)))
		}
		for i := 0; i < len(exp) && i < len(act); i++ {
			diffJSON(fmt.Sprintf("%s[%d]", path, i), exp[i], act[i], diffs)
		}
	default:
		*diffs = append(*diffs, fmt.Sprintf("%s: want %s, got %s", path, describeJSON(expected), describeJSON(actual)))
	}
}

func describeJSON(value any) string {
	data, err := json.Marshal(value)
	if err != nil {
		return fmt.Sprintf("%v", value)
	}
	if len(data) > 120 {
		return string(data[:120]) + "..."
	}
	return string(data)
}
